# Generated by Django 4.1.2 on 2022-10-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayEmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sent', models.BooleanField(default=False)),
                ('recipient', models.CharField(max_length=48)),
                ('date', models.DateField()),
            ],
        ),
    ]
